name: Deploy TaskTim App

on:
  push:
    branches:
      - main

jobs:
  deploy_to_vps:
    runs-on: ubuntu-latest
    steps:
      # Ambil source code terbaru dari repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Sync folder cc_tasktim ke VPS
      - name: Sync app files to VPS
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          source: "cc_tasktim/"
          target: "/home/adit/tasktim_docker/cc_tasktim"
          rm: false   # overwrite file yang berubah saja

      # Restart container agar perubahan langsung diterapkan
      - name: Reload container on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            if docker ps -a --format '{{.Names}}' | grep -Eq '^tastim$'; then
              echo "Restarting container 'tastim'..."
              docker restart tastim
            else
              echo "Container 'tastim' tidak ada. Silakan start container manual."
            fi
