name: Deploy TaskTim App

on:
  push:
    branches:
      - main

jobs:
  deploy_to_vps:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to container on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            cd /home/adit/tasktim_docker/cc_tasktim
            git reset --hard
            git clean -fd
            git pull origin main

            # Copy kode ke container
            docker cp . tastim:/var/www/html

            # Clear cache & autoload
            docker exec tastim bash -c "cd /var/www/html && php spark cache:clear || true"
            docker exec tastim bash -c "cd /var/www/html && composer dump-autoload -o || true"

            # Restart PHP-FPM
            docker exec tastim bash -c "pkill -o -USR2 php-fpm || true"

            echo "âœ… Web updated"
